version: "3"

services:
  api:
    build: ./
    image: bus-schedule-api
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge